export const DEVICE_TYPES = ["switch", "light"] as const;

export const ENCODING_FILE = "utf-8";

export const DEFAULT_OUT_PATH = "./src/ha.ts";
export const DEFAULT_CONFIG_PATH = "./.hasdk.config.json";

// prettier-ignore
export const HEADER = 
`// Generated by Home Assistant device SDK
//
//  /!\\  Don't modify this file manually
// 
// Use hasdk CLI to generate this file
// CMD : npx hasdk -u <url> -t <token> -o <file>
//
// `;

export const IMPORTS_LIST = [``, `import { HaWebSocket, IConnectionConfig, IHandler } from "home-assistant-device-sdk";`];

export const CLASS_INIT_LIST = [
    ``,
    ``,
    `export class HA {`,
    `\tpublic static async connect(config?: IConnectionConfig): Promise<void> {`,
    `\t\tawait HaWebSocket.connect(this, config);`,
    `\t}`,
    `\tpublic static async getStates(): Promise<boolean> {`,
    `\t\treturn HaWebSocket.refreshStates();`,
    `\t}`,
    `\tpublic static set onConnect(callBack: IHandler) {`,
    `\t\tHaWebSocket.onConnect(callBack);`,
    `\t}`,
    `\tpublic static removeOnConnect(callBack: IHandler) {`,
    `\t\tHaWebSocket.removeOnConnect(callBack);`,
    `\t}`,
    ``,
    `\tpublic static readonly devices = {`,
];
